Repository w3c/webcrypto, pull requests merged in 2019-11, with the labels that each got.

#224 Fix some typos in the specification
  spec/Overview-WebCryptoAPI.xml
Labels: editorial, errata

#218 Fix Web IDL extended attribute usage: [EnforceRange] now applies to types
  spec/Overview-WebCryptoAPI.xml
  spec/Overview.html
Labels: errata

#205 SHA algorithms aren't defined in this spec
  spec/Overview-WebCryptoAPI.xml
Labels: editorial, errata

#204 Update in 33.2. Symmetric Encryption example -
  spec/Overview-WebCryptoAPI.xml
  spec/Overview.html
Labels: editorial, errata, needs review

#206 window.crypto returns the same object
  spec/Overview-WebCryptoAPI.xml
Labels: enhancement, errata
